### ISSUE TITLE
Create new link hard to click in some browsers

### ISSUE THREAD

**Issue by xt0rted** [sparkfun/data.sparkfun.com#1]
This isn't an issue with the service, but rather http://data.sparkfun.com itself. The create new link in the top right is mostly covered by the scrollbar in IE10 and 11.

![normal](https://cloud.githubusercontent.com/assets/831974/3543283/1b27da58-0860-11e4-91c9-8fa40dd5ebe6.png) ![hover](https://cloud.githubusercontent.com/assets/831974/3543287/21fca19c-0860-11e4-8346-1d4b17d29d72.png)

This happens because of these style rules

``` css
@-ms-viewport
{
    width: device-width;
}

@media (min-width:768px)
{
    .navbar-nav.navbar-right:last-child
    {
        margin-right:-15px;
    }
}
```

The `@-ms-viewport` rule tells IE to overlay the scrollbar on the window instead of next to it and then the `-15px` margin reset moves the link under it. Removing that rule fixes the issue.
